apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: build-submarine-jbpm-quarkus-example
spec:
  parameters:
  - name: SUBMARINE_BOM_REPO_URL
    description: The url of submarine-bom repo to build.
  - name: SUBMARINE_BOM_REPO_BRANCH
    description: The branch of submarine-bom repo to build.
  - name: SUBMARINE_RUNTIMES_REPO_URL
    description: The url of submarine-runtimes repo to build.
  - name: SUBMARINE_RUNTIMES_REPO_BRANCH
    description: The branch of submarine-runtimes repo to build.
  - name: SUBMARINE_EXAMPLES_REPO_URL
    description: The url of submarine-examples repo to build.
  - name: SUBMARINE_EXAMPLES_REPO_BRANCH
    description: The branch of submarine-examples repo to build.
  - name: SUBMARINE_BOM_CONTEXT_DIR
    description: The context directory from where to run the submarine-bom build.
  - name: SUBMARINE_RUNTIMES_CONTEXT_DIR
    description: The context directory from where to run the submarine-runtimes build.
  - name: SUBMARINE_JBPM_QUARKUS_EXAMPLE_CONTEXT_DIR
    description: The context directory from where to run the submarine-jbpm-quarkus-example build.
  - name: SUBMARINE_JBPM_QUARKUS_EXAMPLE_IMAGE_CONTEXT_DIR
    description: The context directory from where to run the submarine-jbpm-quarkus-example docker build.
  - name: SUBMARINE_JBPM_QUARKUS_EXAMPLE_IMAGE
    description: The name of the image to push.
  steps:
  - args:
    - clean
    - install
    - -Dsubmarine-bom-url=${SUBMARINE_BOM_REPO_URL}
    - -Dsubmarine-bom-branch=${SUBMARINE_BOM_REPO_BRANCH}
    - -Dsubmarine-runtimes-url=${SUBMARINE_RUNTIMES_REPO_URL}
    - -Dsubmarine-runtimes-branch=${SUBMARINE_RUNTIMES_REPO_BRANCH}
    - -Dsubmarine-examples-url=${SUBMARINE_EXAMPLES_REPO_URL}
    - -Dsubmarine-examples-branch=${SUBMARINE_EXAMPLES_REPO_BRANCH}
    image: gcr.io/cloud-builders/mvn
    name: build-submarine-knative
    volumeMounts:
    - mountPath: /builder/home/.m2
      name: m2-cache
    workingDir: /workspace
  - args:
    - clean
    - install
    - -DskipTests=true
    image: gcr.io/cloud-builders/mvn
    name: build-submarine-bom
    volumeMounts:
    - mountPath: /builder/home/.m2
      name: m2-cache
    workingDir: /workspace/${SUBMARINE_BOM_CONTEXT_DIR}
  - args:
    - clean
    - install
    - -DskipTests=true
    image: gcr.io/cloud-builders/mvn
    name: build-submarine-runtimes
    volumeMounts:
    - mountPath: /builder/home/.m2
      name: m2-cache
    workingDir: /workspace/${SUBMARINE_RUNTIMES_CONTEXT_DIR}
  - args:
    - clean
    - package
    image: gcr.io/cloud-builders/mvn
    name: build-submarine-jbpm-quarkus-example
    volumeMounts:
    - mountPath: /builder/home/.m2
      name: m2-cache
    workingDir: /workspace/${SUBMARINE_JBPM_QUARKUS_EXAMPLE_CONTEXT_DIR}
  - args:
    - --context=/workspace/${SUBMARINE_JBPM_QUARKUS_EXAMPLE_IMAGE_CONTEXT_DIR}
    - --dockerfile=/workspace/${SUBMARINE_JBPM_QUARKUS_EXAMPLE_IMAGE_CONTEXT_DIR}/Dockerfile
    - --destination=${SUBMARINE_JBPM_QUARKUS_EXAMPLE_IMAGE}
    - --build-arg=JAR_FILE=${SUBMARINE_JBPM_QUARKUS_JAR_FILE}
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
    image: gcr.io/kaniko-project/executor
    name: push-submarine-jbpm-quarkus-example
    volumeMounts:
    - mountPath: /cache
      name: kaniko-cache
    workingDir: /workspace/${SUBMARINE_JBPM_QUARKUS_EXAMPLE_IMAGE_CONTEXT_DIR}
  volumes:
  - name: m2-cache
    persistentVolumeClaim:
      claimName: m2-cache
  - name: kaniko-cache
    persistentVolumeClaim:
      claimName: kaniko-cache