apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: build-kogito-jbpm-quarkus-example
spec:
  parameters:
  - name: KOGITO_BOM_REPO_URL
    description: The url of kogito-bom repo to build.
  - name: KOGITO_BOM_REPO_BRANCH
    description: The branch of kogito-bom repo to build.
  - name: KOGITO_RUNTIMES_REPO_URL
    description: The url of kogito-runtimes repo to build.
  - name: KOGITO_RUNTIMES_REPO_BRANCH
    description: The branch of kogito-runtimes repo to build.
  - name: KOGITO_EXAMPLES_REPO_URL
    description: The url of kogito-examples repo to build.
  - name: KOGITO_EXAMPLES_REPO_BRANCH
    description: The branch of kogito-examples repo to build.
  - name: KOGITO_BOM_CONTEXT_DIR
    description: The context directory from where to run the kogito-bom build.
  - name: KOGITO_RUNTIMES_CONTEXT_DIR
    description: The context directory from where to run the kogito-runtimes build.
  - name: KOGITO_JBPM_QUARKUS_EXAMPLE_CONTEXT_DIR
    description: The context directory from where to run the kogito-jbpm-quarkus-example build.
  - name: KOGITO_JBPM_QUARKUS_EXAMPLE_IMAGE_CONTEXT_DIR
    description: The context directory from where to run the kogito-jbpm-quarkus-example docker build.
  - name: KOGITO_JBPM_QUARKUS_EXAMPLE_IMAGE
    description: The name of the image to push.
  steps:
  - args:
    - clean
    - install
    - -Dkogito-bom-url=${KOGITO_BOM_REPO_URL}
    - -Dkogito-bom-branch=${KOGITO_BOM_REPO_BRANCH}
    - -Dkogito-runtimes-url=${KOGITO_RUNTIMES_REPO_URL}
    - -Dkogito-runtimes-branch=${KOGITO_RUNTIMES_REPO_BRANCH}
    - -Dkogito-examples-url=${KOGITO_EXAMPLES_REPO_URL}
    - -Dkogito-examples-branch=${KOGITO_EXAMPLES_REPO_BRANCH}
    image: gcr.io/cloud-builders/mvn
    name: build-kogito-knative
    volumeMounts:
    - mountPath: /builder/home/.m2
      name: m2-cache
    workingDir: /workspace
  - args:
    - clean
    - install
    - -DskipTests=true
    image: gcr.io/cloud-builders/mvn
    name: build-kogito-bom
    volumeMounts:
    - mountPath: /builder/home/.m2
      name: m2-cache
    workingDir: /workspace/${KOGITO_BOM_CONTEXT_DIR}
  - args:
    - clean
    - install
    - -DskipTests=true
    image: gcr.io/cloud-builders/mvn
    name: build-kogito-runtimes
    volumeMounts:
    - mountPath: /builder/home/.m2
      name: m2-cache
    workingDir: /workspace/${KOGITO_RUNTIMES_CONTEXT_DIR}
  - args:
    - clean
    - package
    image: gcr.io/cloud-builders/mvn
    name: build-kogito-jbpm-quarkus-example
    volumeMounts:
    - mountPath: /builder/home/.m2
      name: m2-cache
    workingDir: /workspace/${KOGITO_JBPM_QUARKUS_EXAMPLE_CONTEXT_DIR}
  - args:
    - --context=/workspace/${KOGITO_JBPM_QUARKUS_EXAMPLE_IMAGE_CONTEXT_DIR}
    - --dockerfile=/workspace/${KOGITO_JBPM_QUARKUS_EXAMPLE_IMAGE_CONTEXT_DIR}/Dockerfile
    - --destination=${KOGITO_JBPM_QUARKUS_EXAMPLE_IMAGE}
    - --build-arg=TARGET_FILE=${KOGITO_JBPM_QUARKUS_TARGET_FILE}
    env:
    - name: DOCKER_CONFIG
      value: /builder/home/.docker
    image: gcr.io/kaniko-project/executor
    name: push-kogito-jbpm-quarkus-example
    volumeMounts:
    - mountPath: /cache
      name: kaniko-cache
    workingDir: /workspace/${KOGITO_JBPM_QUARKUS_EXAMPLE_IMAGE_CONTEXT_DIR}
  volumes:
  - name: m2-cache
    persistentVolumeClaim:
      claimName: m2-cache
  - name: kaniko-cache
    persistentVolumeClaim:
      claimName: kaniko-cache