apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: kogito-jbpm-quarkus-example
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              revision: master
              url: https://github.com/xiezhang7/kogito-knative.git
          template:
            arguments:
              - name: KOGITO_BOM_REPO_URL
                value: https://github.com/kiegroup/kogito-bom.git
              - name: KOGITO_BOM_REPO_BRANCH
                value: master
              - name: KOGITO_RUNTIMES_REPO_URL
                value: https://github.com/xiezhang7/kogito-runtimes.git
              - name: KOGITO_RUNTIMES_REPO_BRANCH
                value: knative-poc
              - name: KOGITO_EXAMPLES_REPO_URL
                value: https://github.com/xiezhang7/kogito-examples.git
              - name: KOGITO_EXAMPLES_REPO_BRANCH
                value: knative-poc
              - name: KOGITO_BOM_CONTEXT_DIR
                value: target/kogito-bom
              - name: KOGITO_RUNTIMES_CONTEXT_DIR
                value: target/kogito-runtimes
              - name: KOGITO_JBPM_QUARKUS_EXAMPLE_CONTEXT_DIR
                value: target/kogito-examples/jbpm-quarkus-example
              - name: KOGITO_JBPM_QUARKUS_EXAMPLE_IMAGE_CONTEXT_DIR
                value: target/kogito-examples/jbpm-quarkus-example
              - name: KOGITO_JBPM_QUARKUS_TARGET_FILE
                value: jbpm-quarkus-example-8.0.0-SNAPSHOT-runner
              - name: KOGITO_JBPM_QUARKUS_EXAMPLE_IMAGE
                value: xiezhang7/jbpm-quarkus-example:0.1
            name: build-kogito-jbpm-quarkus-example
          timeout: 20m
      revisionTemplate:
        metadata:
          labels:
            app: kogito-jbpm-quarkus-example
        spec:
          container:
            image: xiezhang7/jbpm-quarkus-example:0.1
            ports:
              - containerPort: 8080
          initContainers:
            - name: build-status-checker
              image: quay.io/rhdevelopers/build-status-checker
              args:
                - poll
                - --buildname=build-kogito-jbpm-quarkus-example
          serviceAccountName: build-bot