apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: submarine-jbpm-quarkus-example
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              revision: master
              url: https://github.com/xiezhang7/submarine-knative.git
          template:
            arguments:
              - name: SUBMARINE_BOM_REPO_URL
                value: https://github.com/kiegroup/submarine-bom.git
              - name: SUBMARINE_BOM_REPO_BRANCH
                value: master
              - name: SUBMARINE_RUNTIMES_REPO_URL
                value: https://github.com/xiezhang7/submarine-runtimes.git
              - name: SUBMARINE_RUNTIMES_REPO_BRANCH
                value: knative-poc
              - name: SUBMARINE_EXAMPLES_REPO_URL
                value: https://github.com/xiezhang7/submarine-examples.git
              - name: SUBMARINE_EXAMPLES_REPO_BRANCH
                value: knative-poc
              - name: SUBMARINE_BOM_CONTEXT_DIR
                value: target/submarine-bom
              - name: SUBMARINE_RUNTIMES_CONTEXT_DIR
                value: target/submarine-runtimes
              - name: SUBMARINE_JBPM_QUARKUS_EXAMPLE_CONTEXT_DIR
                value: target/submarine-examples/jbpm-quarkus-example
              - name: SUBMARINE_JBPM_QUARKUS_EXAMPLE_IMAGE_CONTEXT_DIR
                value: target/submarine-examples/jbpm-quarkus-example
              - name: SUBMARINE_JBPM_QUARKUS_JAR_FILE
                value: jbpm-quarkus-example-8.0.0-SNAPSHOT-runner
              - name: SUBMARINE_JBPM_QUARKUS_EXAMPLE_IMAGE
                value: xiezhang7/jbpm-quarkus-example:0.1
            name: build-submarine-jbpm-quarkus-example
          timeout: 20m
      revisionTemplate:
        metadata:
          labels:
            app: submarine-jbpm-quarkus-example
        spec:
          container:
            image: xiezhang7/jbpm-quarkus-example:0.1
            ports:
              - containerPort: 8080